#!/bin/bash

echo 'Bootstrap terminal'
echo '------------------'
echo 'This will reset your terminal, are you sure? (y/N)'

read -p 'Answer: ' reply

if [[ "$reply" =~ ^[Yy]$ ]]
then
   sudo -v
   source ~/.dotfiles/installation/install
fi
