#!/bin/bash

# shellcheck disable=SC2046
# shellcheck disable=SC2086



#install zsh
echo ''
echo ''
echo 'zsh shell installation'
echo '----------------------'
sudo apt update
sudo apt install -y zsh powerline fonts-powerline
sudo usermod -s $(which zsh) $(whoami)
echo '---> DONE'




#clone zsh autosuggestions
echo ''
echo ''
echo 'zsh autosuggestions installation'
echo '----------------------'
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
echo '---> DONE'

#install oh-my-zsh
echo ''
echo ''
echo 'zsh oh-my-zsh installation'
echo '----------------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
echo '---> DONE'






#link p10k theme config file
echo ''
echo ''
echo 'p10k theme customization'
echo '----------------------'
rm -f $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/shell/oh-my-zsh/.p10k.zsh $HOME/.p10k.zsh
echo '---> DONE'




#link zsh preferences
echo ''
echo ''
echo 'zshrc customization'
echo '----------------------'
rm -f $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
echo '---> DONE'





#add global gitignore
echo ''
echo ''
echo 'global gitignore setup'
echo '----------------------'
rm -f $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore
echo '---> DONE'







#link font folder
echo ''
echo ''
echo 'custom fonts setup'
echo '----------------------'
rm -f $HOME/.fonts
ln -s $HOME/.dotfiles/fonts $HOME/.fonts
echo '---> DONE'


#copy ssh config file
echo ''
echo ''
echo 'SSH config import'
echo '----------------------'
echo 'Enter your ssh/config repository'
read -rp 'git ssh or https url (leave blank to skip): ' config_git
if [ -n "$config_git" ]
then
  git clone $config_git $HOME/.dotfiles/shell/ssh/config
  rm -f $HOME/.ssh/config
  ln -s $HOME/.dotfiles/shell/ssh/config/config $HOME/.ssh/config
  echo '---> DONE'
fi





#phpstorm url handler
echo ''
echo ''
echo 'PhpStorm URL Handler installation'
echo '----------------------'
source $HOME/.dotfiles/misc/phpstorm-url-handler/install.sh
echo '---> DONE'





#SublimeText installation
read -p 'Install SublimeText? (y/N): ' reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
	echo ''
	echo ''
	echo 'SublimeText installation'
	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - && sudo apt install -y apt-transport-https && echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list && sudo apt update && sudo apt install -y sublime-text
	echo '----------------------'
	echo '---> DONE'
fi




#PhpStorm installation
read -p 'Install PhpStorm? (y/N): ' reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
	echo ''
	echo ''
	echo 'PhpStorm installation'
	sudo snap install phpstorm --classic
	echo '----------------------'
	echo '---> DONE'
fi



#Tools installation
echo ''
echo ''
echo 'Tools installation (Thunderbird, Telegram, Whatsapp, Libreoffice)'
sudo apt install -y thunderbird telegram-desktop libreoffice
sudo snap install whatsdesk
echo '----------------------'
echo '---> DONE'





#Docker installation
read -p 'Install Docker ? (y/N): ' reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
	echo ''
	echo ''
	echo 'Docker installation'
	sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io 
	sudo groupadd docker 
	sudo usermod -aG docker $USER
	sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
	echo '----------------------'
	echo '---> DONE'
fi





#PHP installation
read -p 'Install PHP 8.0 and Composer? (y/N): ' reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
	echo ''
	echo ''
	echo 'PHP 8.0 and Composer installation'
	sudo apt install -y software-properties-common && sudo add-apt-repository ppa:ondrej/php && sudo apt update && sudo apt install -y php8.0-cli php8.0-xml && curl -sS https://getcomposer.org/installer -o composer-setup.php && sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
	echo '----------------------'
	echo '---> DONE'
fi








echo 'PLEASE REBOOT TO APPLY CHANGES'
echo '----------------------'
