#!/bin/bash

#clone zsh autosuggestions
echo ''
echo ''
echo 'zsh autosuggestions installation'
echo '----------------------'
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
echo '---> DONE'
