#!/bin/bash

#link p10k theme config file
echo ''
echo ''
echo 'p10k theme customization'
echo '----------------------'
rm -f $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/shell/oh-my-zsh/.p10k.zsh $HOME/.p10k.zsh
echo '---> DONE'
