#!/bin/bash

#link p10k theme config file
echo ''
echo ''
echo 'p10k theme customization'
echo '----------------------'

$HOME/.dotfiles/misc/oh-my-zsh-custom/themes/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.dotfiles/misc/oh-my-zsh-custom/themes/powerlevel10k
rm -f $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/shell/oh-my-zsh/.p10k.zsh $HOME/.p10k.zsh
echo '---> DONE'
