#!/bin/bash

#Android Studio installation
read -p 'Install Android Studio ? (y/N): ' reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
	echo ''
	echo ''
	echo 'Android Studio installation'
	sudo snap install android-studio --classic
	echo '----------------------'
	echo '---> DONE'
fi



