#!/bin/bash

#PHP installation
read -p 'Install PHP 8.4 and Composer? (y/N): ' reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
	echo ''
	echo ''
	echo 'PHP 8.4 and Composer installation'
	sudo add-apt-repository ppa:ondrej/php
	sudo apt update
	sudo apt install -y software-properties-common && sudo apt update && sudo apt install -y php8.4-cli php8.4-xml php8.4-mbstring php8.4-intl php8.4-gd php8.4-curl php8.4-mysql php8.4-sqlite3 && curl -sS https://getcomposer.org/installer -o composer-setup.php && sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
	echo '----------------------'
	echo '---> DONE'
fi



