#!/bin/bash

#Tools installation
echo ''
echo ''
echo 'Tools installation (Thunderbird, Telegram, Whatsapp, Libreoffice, htop)'
sudo apt install -y thunderbird telegram-desktop libreoffice htop
sudo snap install whatsdesk
echo '----------------------'
echo '---> DONE'

