#!/bin/bash

#SublimeText installation
read -pr 'Install SublimeText? (y/N): ' reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
	echo ''
	echo ''
	echo 'SublimeText installation'
	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - && sudo apt install -y apt-transport-https && echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list && sudo apt update && sudo apt install -y sublime-text
	echo '----------------------'
	echo '---> DONE'
fi


