#!/bin/bash

#Albert installation
ubuntu_version=$(lsb_release -rs)
read -p "Install Albert for Ubuntu ${ubuntu_version}? (y/N): " reply
if [[ "$reply" =~ ^[Yy]$ ]]
then
  echo ''
	echo ''
	echo 'Albert installation'
  sudo curl https://build.opensuse.org/projects/home:manuelschneid3r/public_key | sudo apt-key add -
  echo "deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_${ubuntu_version}/ /" | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
  sudo wget -nv "https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_${ubuntu_version}/Release.key" -O "/etc/apt/trusted.gpg.d/home:manuelschneid3r.asc"
  sudo apt update
  sudo apt install albert
  albert
	echo '----------------------'
	echo '---> DONE'
fi
