#!/bin/bash

#setup git rerere
echo ''
echo ''
echo 'enable git rerere globally'
echo '----------------------'
git config --global rerere.enabled true
echo '---> DONE'

#add global gitignore
echo ''
echo ''
echo 'global gitignore setup'
echo '----------------------'
rm -f $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore
echo '---> DONE'
