#!/bin/bash

#add global gitignore
echo ''
echo ''
echo 'global gitignore setup'
echo '----------------------'
rm -f $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore
echo '---> DONE'
