#!/bin/bash

#copy ssh config file
echo ''
echo ''
echo 'SSH config import'
echo '----------------------'
echo 'Enter your ssh/config repository'
read -rp 'git ssh or https url (leave blank to skip): ' config_git
if [ -n "$config_git" ]
then
  git clone $config_git $HOME/.dotfiles/shell/ssh/config
  rm -f $HOME/.ssh/config
  ln -s $HOME/.dotfiles/shell/ssh/config/config $HOME/.ssh/config
  echo '---> DONE'
fi
