#!/bin/bash

#Tools installation
echo ''
echo ''
echo 'Tools installation (Thunderbird, Telegram, Whatsapp, Libreoffice, htop, peek)'
sudo apt install -y thunderbird libreoffice htop
sudo snap install --classic telegram-desktop
echo '----------------------'
echo '---> DONE'


