#!/bin/bash

#Tools installation
echo ''
echo ''
echo 'Tools installation (Thunderbird, Telegram, Whatsapp, Libreoffice, htop, peek)'
sudo apt install -y thunderbird telegram-desktop libreoffice htop copyq  peek
sudo snap install whatsdesk
echo '----------------------'
echo '---> DONE'

