#!/bin/bash

#Tools installation
echo ''
echo ''
echo 'Tools installation (Thunderbird, Telegram, Whatsapp, Libreoffice, htop, peek)'
sudo apt install -y thunderbird libreoffice htop
sudo snap install --classic telegram-desktop
echo '----------------------'
echo '---> DONE'

#Agents skills
echo ''
echo ''
echo 'Agents skill sharing'
echo '----------------------'
rm -f $HOME/.agents
ln -s $HOME/.dotfiles/agents $HOME/.agents
echo '---> DONE'


